spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/oauth_jwt
    username: margin
    password: jwmun5508
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  config:
    import: application-oauth.yml

logging.level:
  com.security.oauthjwt: info
  org.hibernate.SQL: debug