spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/jpa_association
    username: margin
    password: jwmun5508
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

logging.level:
  org.hibernate.SQL: debug